// Generated by CoffeeScript 1.6.2
var data, fs, list, path, read, value, _;

fs = require("fs");

path = require("path");

read = function(filename) {
  var filepath;

  filepath = path.join("./posts", filename);
  return console.log(filepath);
};

data = {
  0: require("./posts/about-coder-news"),
  1: require("./posts/future-of-UI"),
  2: require("./posts/why-collect-links"),
  3: require("./posts/love-languages"),
  4: require("./posts/join-communities"),
  5: require("./posts/everyone-gets-old"),
  6: require("./posts/you-and-me-different"),
  6: require("./posts/about-this-site")
};

list = (function() {
  var _results;

  _results = [];
  for (_ in data) {
    value = data[_];
    _results.push(value);
  }
  return _results;
})();

exports.by_time = list;

exports.by_sort = list.sort(function(a, b) {
  return a.title < b.title;
});

console.log(list);
