// Generated by CoffeeScript 1.6.2
exports.title = "这里的页面布局参考了 Medium 和 Kippt, 想要更美观";

exports.image = "http://photos.tuchong.com/48548/f/2057678.jpg";

exports.content = "没有比在纸张上干整齐净排版的网页更适合阅读的, 网页也类似\n看倦了花样繁多的图标, 看到 kippt.com 列表界面的干净我非常喜欢\n同时, 点击书签会展开标题和评论的简单结, 这里做了模仿\n我本来很期待能像 Kippt 一样用明快的图标, 按钮, 分块\n可想到做不出高质量的图标, 逐渐就开始往简单的做了\n\nKippt 的界面颜色非常干净, 也没有杂乱的颜色干扰视野\n于是我尝试模仿 Kippt 和 ulven.org 清晰的黑白色调改了博客\nhttp://jiyinyiyong.github.io/blog/\n意外地加了一大块深色, 为方便阅读使用的白色背景显得不再刺眼\n只是这个页面我不想同样的单调, 于是模仿另一个页面增加了图片\nhttps://medium.com/on-coding/6b6402216740\n链接里顶部的 Node Logo 非常醒目, 网页不再是单调\n只是我思来想去, 不知道怎么控制好图片, 索性先放全屏了\n\n见过 Svbtle 那种极简风格, 于是也留意了下 Medium\n网上介绍 Medium 是 Twtitter 联合创始人介绍的网站, 包含了很多反思\n我在网上搜到视觉中国的一组界面, 看完我很喜欢 Medium 的风格\nhttp://shijue.me/show_idea/5126c8828ddf87160e0011f9\n简洁明确的界面, 整洁美观的布局, 让人感到阅读的舒适\n\n介绍的文章里有一句话我很赞同, 纸张已经有很多年使用的历史,\n而互联网只有短短几十年, 互联网要学的东西还有很多\n我个人期待看到的是网页上的布局和文本有更好的可读性\n网页是排版干净的一段文字, 打开就能被清晰地阅读\n大概没有那样的技能也是个遗憾, 不管了以后再说吧..\n看优秀的作品会知道设计方向上有多远多远\nhttp://www.zhihu.com/question/20951814";
