// Generated by CoffeeScript 1.4.0
var delay, log, q;

log = function() {
  return typeof console !== "undefined" && console !== null ? typeof console.log === "function" ? console.log.apply(console, arguments) : void 0 : void 0;
};

delay = function(f, t) {
  return setTimeout(t, f);
};

q = function(query) {
  return document.querySelector(query);
};

Node.prototype.q = function(query) {
  return this.querySelector(query);
};

Object.getOwnPropertyNames(Array.prototype).forEach(function(prop) {
  if (Array.prototype[prop] != null) {
    if ((typeof Array.prototype[prop]) === "function") {
      return NodeList.prototype[prop] = Array.prototype[prop];
    }
  }
});

window.onload = function() {};
